#1.Zeros function

In [1]:
import numpy as np
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [2]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

#2.eye function


In [3]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

#3.Diagonal function


In [5]:
arr=np.diag([1,5,3,7])
np.diag(arr)
arr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

#4.generate random number

In [6]:
arr=np.random.randint(1,10,3)
arr

array([9, 2, 7])

#5.rand fuunction


In [7]:
arry=np.random.rand(5)
arr

array([9, 2, 7])

In [8]:
arry=np.random.randn(5)
arry

array([ 0.29763153, -0.1723125 , -0.63000128,  0.3322382 , -0.08044459])

#6.view and copy of array

In [9]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
b=a[3:6]
b

array([40, 50, 60])

In [10]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [11]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#7.Numpy in pythhon conditional selection

In [12]:
import numpy as np
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
import numpy as np
arr=np.arange(1,16)
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [14]:
# import numpy as np
# arr=np.arange(1,16)
# arr[arr>10]
import numpy as np
arr= np.arange(1,15)
arr[arr>10]

array([11, 12, 13, 14])

In [15]:
import numpy as np
arr=np.arange(1,16)
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [16]:
import numpy as np
arr=np.arange(1,16)
arr[arr%2==0]=0
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

#8.Various opration on numpy array

In [17]:
import numpy as np
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [18]:
arr+2

array([3, 4, 5, 6])

In [19]:
arr*2

array([2, 4, 6, 8])

In [20]:
arr**2

array([ 1,  4,  9, 16])

##9.**Operation on 2D marix**

In [21]:
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)


In [22]:
a

array([[1, 2],
       [3, 4]])

In [23]:
b

array([[5, 6],
       [7, 8]])

In [24]:
a+b


array([[ 6,  8],
       [10, 12]])

In [25]:
a.dot(b)

array([[19, 22],
       [43, 50]])

#10. **some more fuction of num**



In [26]:
import numpy as np
a=np.array([10,20,30,40,50,60])
np.min(a)


10

In [27]:
np.max(a)

60

In [28]:
np.argmax(a)

5

In [29]:
np.argmin(a)

0

In [30]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [31]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [32]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

#11.  **Another  most important function**

---



In [35]:
import numpy as np
a=np.array([10,20,30,40,50])
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#12.**Creating 2D array with fixed datatype**

---



In [36]:
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [37]:
np.sum(matrix)

116

In [38]:
np.max(matrix)

17

In [39]:
np.min(matrix,axis=1)

array([11, 13,  3])

In [41]:
np.max(matrix,axis=0)

array([17, 16, 16])

In [42]:
np.sum(matrix, axis=1)

array([40, 46, 30])

#13.Python Numpy stacking

In [43]:
import numpy as np
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(31,51,9).reshape(3,3)
arr1


array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [44]:
import numpy as np
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(31,51,9).reshape(3,3)
np.hstack((arr1,arr2))


array([[16, 11, 13, 40, 37, 45],
       [17, 13, 16, 34, 35, 50],
       [ 3, 16, 11, 50, 44, 31]])

#14. List vs numpy

In [45]:
%timeit[i**2 for i in range (1,11)]

UsageError: Line magic function `%timeit[i**2` not found.


In [46]:
import numpy as np
%timeit np.arange(1,11)**2

1.38 µs ± 22.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#15.Numpy searching Arrays

In [47]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
x= np.where(arr==40)
x

(array([3]),)

In [48]:
import numpy as np
a=np.array([10,20,30,40,50,60])
x=np.searchsorted(a,70
                  )
print(x)

6
